DROP DATABASE IF EXISTS burgers_DB;
CREATE DATABASE burgers_DB;
USE burgers_DB;

CREATE TABLE burgers (
    PRIMARY KEY id INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(300) NOT NULL,
    devoured BOOLEAN NOT NULL
);